### ISSUE TITLE
Integration with CodeRunBot

### ISSUE THREAD

**Issue by gaato** [gaato/coderunbot#3]
Run CodeRunBot again, which had been stopped. So we aim to run two bots by sharing common code in this repository.

# ToDo
- [x] Create the run command
- [x] Apply for CodeRunBot's message content intent
- [x] ~~Using [ThreadPoolExecutor](https://docs.python.org/ja/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) to run two bots~~ Use different command line arguments

**Comment by gaato** [comment]
```
Traceback (most recent call last):
  File "/home/gaato/dev/gaato/gaato-bot/gaato_bot/core/bot.py", line 30, in run
    self.loop.run_until_complete(self.start(self.token))
  File "/home/gaato/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 617, in run_until_complete
    self._check_running()
  File "/home/gaato/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 577, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```
